# Generated by Django for NIR Intelligence Platform

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wavelengths', models.JSONField(default=list)),
                ('intensities', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('spectrometer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('data_quality_score', models.FloatField(blank=True, null=True)),
                ('metadata_quality_score', models.FloatField(blank=True, null=True)),
                ('calibration_quality_score', models.FloatField(blank=True, null=True)),
                ('overall_quality_score', models.FloatField(blank=True, null=True)),
                ('analysis_results', models.JSONField(default=dict)),
                ('calibration_results', models.JSONField(default=dict)),
                ('metadata_quality_results', models.JSONField(default=dict)),
                ('federated_consent', models.BooleanField(default=False)),
                ('is_federated', models.BooleanField(default=False)),
                ('federation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisproject')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('report_type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_query', models.TextField()),
                ('agent_response', models.TextField()),
                ('agent_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spectral_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.spectraldata')),
                ('calibration_type', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('formula', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
