# Generated by Django for NIR Intelligence Platform

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wavelengths', models.JSONField(default=list)),
                ('intensities', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('spectrometer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('data_quality_score', models.FloatField(blank=True, null=True)),
                ('metadata_quality_score', models.FloatField(blank=True, null=True)),
                ('calibration_quality_score', models.FloatField(blank=True, null=True)),
                ('overall_quality_score', models.FloatField(blank=True, null=True)),
                ('analysis_results', models.JSONField(default=dict)),
                ('calibration_results', models.JSONField(default=dict)),
                ('metadata_quality_results', models.JSONField(default=dict)),
                ('federated_consent', models.BooleanField(default=False)),
                ('is_federated', models.BooleanField(default=False)),
                ('federation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spectral Data',
                'verbose_name_plural': 'Spectral Data',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('spectral_data', models.ManyToManyField(related_name='projects', to='analysis.spectraldata')),
            ],
            options={
                'verbose_name': 'Analysis Project',
                'verbose_name_plural': 'Analysis Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spectral_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analysis.spectraldata')),
                ('report_type', models.CharField(default='spectral_analysis', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('quarto_content', models.TextField()),
                ('html_content', models.TextField(blank=True, null=True)),
                ('python_source', models.TextField(blank=True, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('spectral_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.spectraldata')),
                ('session_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_type', models.CharField(default='analysis', max_length=100)),
                ('messages', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spectral_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.spectraldata')),
                ('calibration_type', models.CharField(max_length=100)),
                ('calibration_data', models.JSONField(default=dict)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('calibration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calibration History',
                'verbose_name_plural': 'Calibration Histories',
                'ordering': ['-calibration_date'],
            },
        ),
    ]
