# Generated by Django 6.0.7 on 2026-08-03 12:01

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Agent Name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='Version')),
                ('agent_file', models.CharField(max_length=200, verbose_name='Agent File')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='Capabilities')),
                ('supported_formats', models.JSONField(blank=True, default=list, verbose_name='Supported Formats')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, verbose_name='Parameters Schema')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='Dependencies')),
                ('status', models.CharField(choices=[('available', 'Available'), ('running', 'Running'), ('disabled', 'Disabled'), ('error', 'Error')], default='available', max_length=20, verbose_name='Status')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('average_execution_time', models.FloatField(blank=True, null=True, verbose_name='Avg Execution Time (s)')),
                ('success_rate', models.FloatField(default=0.0, verbose_name='Success Rate (%)')),
                ('total_executions', models.IntegerField(default=0, verbose_name='Total Executions')),
                ('successful_executions', models.IntegerField(default=0, verbose_name='Successful Executions')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('license', models.CharField(blank=True, max_length=50, verbose_name='License')),
                ('documentation', models.URLField(blank=True, verbose_name='Documentation URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='Last Executed')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Institution')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('preferred_language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('theme_preference', models.CharField(default='light', max_length=10, verbose_name='Theme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NIRSpectrum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Spectrum Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sample_id', models.CharField(blank=True, max_length=100, verbose_name='Sample ID')),
                ('sample_type', models.CharField(blank=True, max_length=100, verbose_name='Sample Type')),
                ('sample_source', models.CharField(blank=True, max_length=200, verbose_name='Sample Source')),
                ('spectral_type', models.CharField(choices=[('absorbance', 'Absorbance'), ('reflectance', 'Reflectance'), ('transmittance', 'Transmittance')], default='absorbance', max_length=20, verbose_name='Spectral Type')),
                ('data_format', models.CharField(choices=[('txt', 'Text File'), ('csv', 'CSV File'), ('json', 'JSON File'), ('h5', 'HDF5 File')], default='txt', max_length=10, verbose_name='Data Format')),
                ('original_file', models.FileField(upload_to='spectra/original/', verbose_name='Original File')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='spectra/processed/', verbose_name='Processed File')),
                ('wavelength_range_start', models.FloatField(verbose_name='Wavelength Start (nm)')),
                ('wavelength_range_end', models.FloatField(verbose_name='Wavelength End (nm)')),
                ('resolution', models.FloatField(verbose_name='Resolution (nm)')),
                ('data_points', models.IntegerField(verbose_name='Number of Data Points')),
                ('instrument', models.CharField(blank=True, max_length=200, verbose_name='Instrument')),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Collection Date')),
                ('collection_conditions', models.JSONField(blank=True, default=dict, verbose_name='Collection Conditions')),
                ('mean_absorbance', models.FloatField(blank=True, null=True, verbose_name='Mean Absorbance')),
                ('max_absorbance', models.FloatField(blank=True, null=True, verbose_name='Max Absorbance')),
                ('min_absorbance', models.FloatField(blank=True, null=True, verbose_name='Min Absorbance')),
                ('peaks_detected', models.IntegerField(default=0, verbose_name='Peaks Detected')),
                ('signal_to_noise_ratio', models.FloatField(blank=True, null=True, verbose_name='S/N Ratio')),
                ('baseline_corrected', models.BooleanField(default=False, verbose_name='Baseline Corrected')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='Quality Score')),
                ('status', models.CharField(default='uploaded', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'NIR Spectrum',
                'verbose_name_plural': 'NIR Spectra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Job Name')),
                ('job_type', models.CharField(choices=[('spectral_analysis', 'Spectral Analysis'), ('quality_control', 'Quality Control'), ('peak_detection', 'Peak Detection'), ('baseline_correction', 'Baseline Correction'), ('noise_reduction', 'Noise Reduction'), ('classification', 'Classification'), ('regression', 'Regression'), ('custom', 'Custom Analysis')], default='spectral_analysis', max_length=50, verbose_name='Job Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Agent Name')),
                ('agent_version', models.CharField(blank=True, max_length=20, verbose_name='Agent Version')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='Results')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.FloatField(default=0.0, verbose_name='Progress (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Execution Time (s)')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='Memory Usage (MB)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('spectra', models.ManyToManyField(related_name='analysis_jobs', to='core.nirspectrum', verbose_name='Spectra')),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'verbose_name_plural': 'Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Module')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='Function')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Context')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Stack Trace')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Theme')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Timezone')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('job_completion_notifications', models.BooleanField(default=True, verbose_name='Job Completion Notifications')),
                ('error_notifications', models.BooleanField(default=True, verbose_name='Error Notifications')),
                ('auto_process_uploads', models.BooleanField(default=False, verbose_name='Auto Process Uploads')),
                ('max_storage_usage', models.IntegerField(default=1000, verbose_name='Max Storage (MB)')),
                ('auto_cleanup_old_files', models.BooleanField(default=False, verbose_name='Auto Cleanup Old Files')),
                ('retention_days', models.IntegerField(default=30, verbose_name='Retention Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('default_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='core.agent', verbose_name='Default Agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='nirspectrum',
            index=models.Index(fields=['user', 'created_at'], name='core_nirspe_user_id_c433c3_idx'),
        ),
        migrations.AddIndex(
            model_name='nirspectrum',
            index=models.Index(fields=['sample_type'], name='core_nirspe_sample__cdc63c_idx'),
        ),
        migrations.AddIndex(
            model_name='nirspectrum',
            index=models.Index(fields=['status'], name='core_nirspe_status_02cae2_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['user', 'created_at'], name='core_analys_user_id_6ac87d_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status'], name='core_analys_status_50f99e_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['job_type'], name='core_analys_job_typ_870b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['timestamp'], name='core_system_timesta_7e67e4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level'], name='core_system_level_bf5286_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['module'], name='core_system_module_fa9e10_idx'),
        ),
    ]
