# Generated by Django 6.0.7 on 2026-08-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='data_visibility',
            field=models.CharField(choices=[('private', 'Private (Local Only)'), ('public', 'Public (Shared with all users)'), ('federated', 'Federated (Shared with FlowerAI network)')], default='private', max_length=20, verbose_name='Data Visibility'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='federated_learning_enabled',
            field=models.BooleanField(default=True, verbose_name='Federated Learning Enabled'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='flowerai_client_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='FlowerAI Client ID'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='flowerai_enabled',
            field=models.BooleanField(default=True, verbose_name='FlowerAI Enabled'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='flowerai_server_url',
            field=models.URLField(blank=True, verbose_name='FlowerAI Server URL'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ilias_enabled',
            field=models.BooleanField(default=True, verbose_name='ILIAS Integration Enabled'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ilias_session_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='ILIAS Session Token'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ilias_sync_enabled',
            field=models.BooleanField(default=True, verbose_name='ILIAS Synchronization Enabled'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='ilias_user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ILIAS User ID'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='share_analysis_results',
            field=models.BooleanField(default=True, verbose_name='Share Analysis Results'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='share_metadata',
            field=models.BooleanField(default=True, verbose_name='Share Metadata'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='share_spectra_data',
            field=models.BooleanField(default=True, verbose_name='Share Spectra Data'),
        ),
    ]
