# Generated by Django 6.0.7 on 2026-08-11 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='files/thumbnails/', verbose_name='Thumbnail')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='files/previews/', verbose_name='Preview File')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='File Size (bytes)')),
                ('file_extension', models.CharField(max_length=20, verbose_name='File Extension')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('file_category', models.CharField(choices=[('spectral', 'Spectral Data'), ('tabular', 'Tabular Data'), ('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('archive', 'Archive'), ('document', 'Document'), ('binary', 'Binary'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='File Category')),
                ('content_metadata', models.JSONField(blank=True, default=dict, verbose_name='Content Metadata')),
                ('num_rows', models.IntegerField(blank=True, null=True, verbose_name='Number of Rows')),
                ('num_columns', models.IntegerField(blank=True, null=True, verbose_name='Number of Columns')),
                ('column_names', models.JSONField(blank=True, default=list, verbose_name='Column Names')),
                ('data_types', models.JSONField(blank=True, default=dict, verbose_name='Data Types')),
                ('num_lines', models.IntegerField(blank=True, null=True, verbose_name='Number of Lines')),
                ('num_words', models.IntegerField(blank=True, null=True, verbose_name='Number of Words')),
                ('num_characters', models.IntegerField(blank=True, null=True, verbose_name='Number of Characters')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('image_channels', models.IntegerField(blank=True, null=True, verbose_name='Image Channels')),
                ('image_format', models.CharField(blank=True, max_length=20, verbose_name='Image Format')),
                ('audio_duration', models.FloatField(blank=True, null=True, verbose_name='Audio Duration (seconds)')),
                ('audio_sample_rate', models.IntegerField(blank=True, null=True, verbose_name='Audio Sample Rate')),
                ('audio_channels', models.IntegerField(blank=True, null=True, verbose_name='Audio Channels')),
                ('audio_bit_rate', models.IntegerField(blank=True, null=True, verbose_name='Audio Bit Rate')),
                ('video_duration', models.FloatField(blank=True, null=True, verbose_name='Video Duration (seconds)')),
                ('video_resolution', models.CharField(blank=True, max_length=20, verbose_name='Video Resolution')),
                ('video_frame_rate', models.FloatField(blank=True, null=True, verbose_name='Video Frame Rate')),
                ('video_codec', models.CharField(blank=True, max_length=50, verbose_name='Video Codec')),
                ('archive_contents', models.JSONField(blank=True, default=list, verbose_name='Archive Contents')),
                ('archive_num_files', models.IntegerField(blank=True, null=True, verbose_name='Number of Files in Archive')),
                ('md5_hash', models.CharField(blank=True, max_length=64, verbose_name='MD5 Hash')),
                ('sha1_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA1 Hash')),
                ('sha256_hash', models.CharField(blank=True, max_length=128, verbose_name='SHA256 Hash')),
                ('quality_score', models.FloatField(default=0.0, verbose_name='Quality Score')),
                ('quality_grade', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('unacceptable', 'Unacceptable'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Quality Grade')),
                ('quality_issues', models.JSONField(blank=True, default=list, verbose_name='Quality Issues')),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('error', 'Error'), ('failed', 'Failed')], default='uploaded', max_length=20, verbose_name='Processing Status')),
                ('processing_results', models.JSONField(blank=True, default=dict, verbose_name='Processing Results')),
                ('analysis_results', models.JSONField(blank=True, default=dict, verbose_name='Analysis Results')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Recommendations')),
                ('processed_by_agent', models.CharField(blank=True, max_length=100, verbose_name='Processed By Agent')),
                ('agent_version', models.CharField(blank=True, max_length=20, verbose_name='Agent Version')),
                ('processing_parameters', models.JSONField(blank=True, default=dict, verbose_name='Processing Parameters')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('custom_metadata', models.JSONField(blank=True, default=dict, verbose_name='Custom Metadata')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is Processed')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='Is Analyzed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analyzed At')),
                ('spectral_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_file', to='core.nirspectrum', verbose_name='Related Spectral Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_files', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Generic File',
                'verbose_name_plural': 'Generic Files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_generi_user_id_1bdac5_idx'), models.Index(fields=['file_category'], name='core_generi_file_ca_f2017a_idx'), models.Index(fields=['processing_status'], name='core_generi_process_770b45_idx'), models.Index(fields=['quality_grade'], name='core_generi_quality_49d7b2_idx'), models.Index(fields=['is_valid'], name='core_generi_is_vali_eac90c_idx'), models.Index(fields=['is_processed'], name='core_generi_is_proc_53286a_idx'), models.Index(fields=['is_analyzed'], name='core_generi_is_anal_6a35cb_idx')],
            },
        ),
    ]
