# Generated by Django 6.1.1 on 2026-09-23 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_genericfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phase', models.CharField(choices=[('drafted', 'Drafted (Preparation)'), ('released', 'Released (Analysis)'), ('completed', 'Completed')], default='drafted', max_length=20, verbose_name='Phase')),
                ('preparation_report', models.JSONField(blank=True, default=dict, verbose_name='Preparation Report (Phase 1)')),
                ('crew_results', models.JSONField(blank=True, default=dict, verbose_name='Crew Analysis Results (Phase 2)')),
                ('final_report_path', models.CharField(blank=True, max_length=512, verbose_name='Final Quarto Report Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Released At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('files', models.ManyToManyField(blank=True, related_name='analysis_projects', to='core.genericfile', verbose_name='Project Files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_projects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Analysis Project',
                'verbose_name_plural': 'Analysis Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'phase'], name='core_analys_user_id_e826fa_idx'), models.Index(fields=['created_at'], name='core_analys_created_126afa_idx')],
            },
        ),
    ]
