# Generated by Django 6.1.1 on 2026-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analysisproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisproject',
            name='metadata_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata Overrides (User)'),
        ),
    ]
