# Generated by Django 6.1.1 on 2026-09-23 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analysisproject_metadata_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=512, verbose_name='Source File Name')),
                ('visibility', models.CharField(choices=[('private', 'Private (owner only)'), ('lab_shared', 'Shared within the lab')], default='private', max_length=20, verbose_name='Visibility')),
                ('wavelengths', models.JSONField(default=list, verbose_name='Wavelengths (nm)')),
                ('intensities', models.JSONField(default=list, verbose_name='Intensities')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('wavelength_grid', models.CharField(blank=True, db_index=True, help_text='Rounded wavelength axis key, e.g. "410.0,435.0,...,940.0"', max_length=255, verbose_name='Wavelength Grid Key')),
                ('instrument_type', models.CharField(blank=True, max_length=255, verbose_name='Instrument Type')),
                ('sample_type', models.CharField(blank=True, max_length=255, verbose_name='Sample Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectrum_records', to='core.analysisproject', verbose_name='Source Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Spectrum Record',
                'verbose_name_plural': 'Spectrum Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'visibility'], name='core_spectr_user_id_f20566_idx'), models.Index(fields=['wavelength_grid'], name='core_spectr_wavelen_4aa369_idx')],
            },
        ),
    ]
