# Generated by Django 6.1.1 on 2026-10-06 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_spectrumrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_key', models.CharField(db_index=True, help_text='Canonical sensor name/model the document belongs to', max_length=255, verbose_name='Sensor Key')),
                ('file', models.FileField(upload_to='sensor_docs/%Y/%m/%d/', verbose_name='Document File')),
                ('original_name', models.CharField(max_length=512, verbose_name='Original File Name')),
                ('doc_type', models.CharField(default='document', max_length=40, verbose_name='Document Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('visibility', models.CharField(choices=[('private', 'Private (owner only)'), ('lab_shared', 'Shared within the lab')], default='lab_shared', max_length=20, verbose_name='Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
            options={
                'verbose_name': 'Sensor Document',
                'verbose_name_plural': 'Sensor Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor_key', 'visibility'], name='core_sensor_sensor__8de356_idx')],
            },
        ),
    ]
