# Generated by Django 6.1.1 on 2026-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sensordocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordocument',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datenblatt'), ('manual', 'Handbuch / Anleitung'), ('calibration', 'Kalibrierung / Zertifikat'), ('photo', 'Foto'), ('software', 'Software / Treiber / Skript'), ('publication', 'Publikation / Referenz'), ('other', 'Sonstiges')], default='other', max_length=40, verbose_name='Document Type'),
        ),
    ]
