# Generated by Django 6.1.2 on 2026-10-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sensordocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nirspectrum',
            name='intensities',
            field=models.JSONField(blank=True, default=list, verbose_name='Intensities'),
        ),
        migrations.AddField(
            model_name='nirspectrum',
            name='wavelengths',
            field=models.JSONField(blank=True, default=list, verbose_name='Wavelengths'),
        ),
        migrations.AddField(
            model_name='nirspectrum',
            name='x_unit',
            field=models.CharField(blank=True, default='nm', max_length=20, verbose_name='X-Axis Unit'),
        ),
        migrations.AddField(
            model_name='nirspectrum',
            name='y_unit',
            field=models.CharField(blank=True, default='a.u.', max_length=40, verbose_name='Y-Axis Unit'),
        ),
    ]
