# Generated by Django 6.1.2 on 2026-10-08 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_nirspectrum_intensities_nirspectrum_wavelengths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature', models.CharField(db_index=True, max_length=32, verbose_name='Spalten-Signatur')),
                ('hints', models.JSONField(default=dict, verbose_name='Bestätigte Struktur-Hinweise')),
                ('confirmed_count', models.IntegerField(default=1, verbose_name='Bestätigungen')),
                ('last_file_name', models.CharField(blank=True, max_length=255, verbose_name='Letzte Datei')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Struktur-Profil',
                'verbose_name_plural': 'Struktur-Profile',
                'constraints': [models.UniqueConstraint(fields=('user', 'signature'), name='unique_user_structure_signature')],
            },
        ),
    ]
