# Generated by Django 6.1.2 on 2026-10-09 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_structureprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station', models.IntegerField(choices=[(1, 'Project Setup'), (2, 'Ingest & Data Basis'), (3, 'Sensor Assignment'), (4, 'Spectrum Comparison'), (5, 'Analysis Cycle'), (6, 'Final Report')], verbose_name='Station Number')),
                ('state', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_user', 'Awaiting User Decision'), ('done', 'Done')], default='open', max_length=20, verbose_name='State')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Station Detail')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stations', to='core.analysisproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Workflow Station',
                'verbose_name_plural': 'Workflow Stations',
                'ordering': ['project', 'station'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Question')),
                ('options', models.JSONField(default=list, verbose_name='Options')),
                ('ki_basis', models.TextField(blank=True, verbose_name='AI Basis')),
                ('answer', models.JSONField(blank=True, default=dict, verbose_name='Answer (option_id, effect, values)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_decisions', to='core.analysisproject', verbose_name='Project')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.workflowstation', verbose_name='Workflow Station')),
            ],
            options={
                'verbose_name': 'Workflow Decision',
                'verbose_name_plural': 'Workflow Decisions',
                'ordering': ['project', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowstation',
            index=models.Index(fields=['project', 'state'], name='core_workfl_project_a966a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstation',
            unique_together={('project', 'station')},
        ),
        migrations.AddIndex(
            model_name='workflowdecision',
            index=models.Index(fields=['project', 'resolved_at'], name='core_workfl_project_b0f379_idx'),
        ),
    ]
